#!/usr/bin/env python3
"""Convert selected Codex Pet v2 cells into low-cost RGB565 firmware frames."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import shutil
import struct
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = Path.home() / ".codex" / "pets" / "lando" / "spritesheet.webp"
DEFAULT_OUTPUT_BIN = ROOT / "firmware" / "components" / "ui" / "assets" / "lando_screensaver.rgb565"
DEFAULT_OUTPUT_HEADER = ROOT / "firmware" / "components" / "ui" / "assets" / "lando_screensaver_asset.h"

ATLAS_WIDTH = 1536
ATLAS_HEIGHT = 2288
CELL_WIDTH = 192
CELL_HEIGHT = 208
DEFAULT_BACKGROUND = "3A454C"

FRAME_GROUPS = (
    ("IDLE", 0, tuple(range(6))),
    ("WAVE", 3, tuple(range(4))),
)


def parse_hex_color(value: str) -> tuple[int, int, int]:
    normalized = value.strip().removeprefix("#")
    if len(normalized) != 6:
        raise ValueError("background must be a six-digit RGB hex color")
    try:
        color = int(normalized, 16)
    except ValueError as error:
        raise ValueError("background must be a six-digit RGB hex color") from error
    return (color >> 16) & 0xFF, (color >> 8) & 0xFF, color & 0xFF


def composite_rgb565(pixel: tuple[int, int, int, int], background: tuple[int, int, int]) -> bytes:
    red, green, blue, alpha = pixel
    inverse = 255 - alpha
    red = (red * alpha + background[0] * inverse + 127) // 255
    green = (green * alpha + background[1] * inverse + 127) // 255
    blue = (blue * alpha + background[2] * inverse + 127) // 255
    packed = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
    return struct.pack("<H", packed)


def identify_dimensions(source: Path) -> tuple[int, int]:
    result = subprocess.run(
        ["magick", "identify", "-format", "%w %h", str(source)],
        check=True,
        capture_output=True,
        text=True,
    )
    width, height = result.stdout.strip().split()
    return int(width), int(height)


def decode_rgba(source: Path, output: Path) -> None:
    subprocess.run(
        ["magick", str(source), "-depth", "8", f"RGBA:{output}"],
        check=True,
    )


def selected_frames(raw_rgba: bytes, background: tuple[int, int, int]) -> bytes:
    atlas_stride = ATLAS_WIDTH * 4
    output = bytearray()
    for _, row, columns in FRAME_GROUPS:
        for column in columns:
            left = column * CELL_WIDTH
            top = row * CELL_HEIGHT
            for y in range(CELL_HEIGHT):
                row_start = (top + y) * atlas_stride + left * 4
                row_end = row_start + CELL_WIDTH * 4
                pixels = raw_rgba[row_start:row_end]
                for offset in range(0, len(pixels), 4):
                    output.extend(composite_rgb565(tuple(pixels[offset:offset + 4]), background))
    return bytes(output)


def render_header(source_sha256: str, background_hex: str) -> str:
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/generate_lando_screensaver_asset.py.",
        f"#define LANDO_SCREENSAVER_SOURCE_SHA256 \"{source_sha256}\"",
        f"#define LANDO_SCREENSAVER_PANEL_COLOR_HEX 0x{background_hex}",
        f"#define LANDO_SCREENSAVER_FRAME_WIDTH {CELL_WIDTH}",
        f"#define LANDO_SCREENSAVER_FRAME_HEIGHT {CELL_HEIGHT}",
        f"#define LANDO_SCREENSAVER_FRAME_BYTES {CELL_WIDTH * CELL_HEIGHT * 2}",
    ]
    frame_offset = 0
    for name, _, columns in FRAME_GROUPS:
        lines.append(f"#define LANDO_SCREENSAVER_{name}_START {frame_offset}")
        lines.append(f"#define LANDO_SCREENSAVER_{name}_COUNT {len(columns)}")
        frame_offset += len(columns)
    lines.extend([
        f"#define LANDO_SCREENSAVER_FRAME_COUNT {frame_offset}",
        f"#define LANDO_SCREENSAVER_ASSET_BYTES {frame_offset * CELL_WIDTH * CELL_HEIGHT * 2}",
        "",
    ])
    return "\n".join(lines)


def write_if_changed(path: Path, payload: bytes) -> None:
    if path.is_file() and path.read_bytes() == payload:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_bytes(payload)
    temporary.replace(path)


def generate(source: Path, output_bin: Path, output_header: Path, background_hex: str, check: bool) -> None:
    if shutil.which("magick") is None:
        raise SystemExit("ImageMagick 'magick' is required")
    if not source.is_file():
        raise SystemExit(f"Lando spritesheet not found: {source}")
    dimensions = identify_dimensions(source)
    if dimensions != (ATLAS_WIDTH, ATLAS_HEIGHT):
        raise SystemExit(
            f"Expected a Codex Pet v2 atlas at {ATLAS_WIDTH}x{ATLAS_HEIGHT}, got {dimensions[0]}x{dimensions[1]}"
        )

    background = parse_hex_color(background_hex)
    normalized_background = background_hex.strip().removeprefix("#").upper()
    source_sha256 = hashlib.sha256(source.read_bytes()).hexdigest()
    with tempfile.TemporaryDirectory(prefix="lando-screensaver-") as temporary_dir:
        rgba_path = Path(temporary_dir) / "atlas.rgba"
        decode_rgba(source, rgba_path)
        raw_rgba = rgba_path.read_bytes()
    expected_rgba_bytes = ATLAS_WIDTH * ATLAS_HEIGHT * 4
    if len(raw_rgba) != expected_rgba_bytes:
        raise SystemExit(f"Decoded atlas has {len(raw_rgba)} bytes; expected {expected_rgba_bytes}")

    binary = selected_frames(raw_rgba, background)
    header = render_header(source_sha256, normalized_background).encode()
    if check:
        mismatches = []
        if not output_bin.is_file() or output_bin.read_bytes() != binary:
            mismatches.append(str(output_bin))
        if not output_header.is_file() or output_header.read_bytes() != header:
            mismatches.append(str(output_header))
        if mismatches:
            raise SystemExit("Lando firmware assets are stale: " + ", ".join(mismatches))
        print(f"Lando firmware asset verified: {len(binary)} bytes, background #{normalized_background}")
        return

    write_if_changed(output_bin, binary)
    write_if_changed(output_header, header)
    print(f"Generated {len(binary)} bytes from {source}")
    print(f"Panel background: #{normalized_background}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output-bin", type=Path, default=DEFAULT_OUTPUT_BIN)
    parser.add_argument("--output-header", type=Path, default=DEFAULT_OUTPUT_HEADER)
    parser.add_argument("--background", default=DEFAULT_BACKGROUND)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        generate(
            args.source.expanduser().resolve(),
            args.output_bin.expanduser().resolve(),
            args.output_header.expanduser().resolve(),
            args.background,
            args.check,
        )
    except (ValueError, subprocess.CalledProcessError) as error:
        raise SystemExit(str(error)) from error


if __name__ == "__main__":
    main()
